### ISSUE TITLE
Reactivate multigateway C2D tests

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1022]
Multigateway C2D tests are disabled. We should check if the processing is now less flaky in the new version
Test_OTAA_Unconfirmed_Receives_Confirmed_C2D_Message
Test_OTAA_Unconfirmed_Receives_Confirmed_FPort_2_Message

**Comment by danigian** [comment]
Successful run [here](https://github.com/Azure/iotedge-lorawan-starterkit/runs/4924091404)
Will retry more times in the next days

**Comment by danigian** [comment]
Tests are failing with new configuration. This requires more investigation on how to handle abandoning of messages

**Comment by danigian** [comment]
#1549 should solve the instability for these tests. We will try it out as soon as the PR is in dev
