### ISSUE TITLE
The frontpage should show an up-to-date overview of the current feature set

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#1051]
Currently the front page of both the documentation and the github repo is outdated and shows duplicate information.
Instead, it should show an up-to-date overview of the current supported feature set, and link into the relevant feature details such as regional support, scenarios, etc ...

It needs to be a good one-pager that can be used as an ["elevator pitch](https://en.wikipedia.org/wiki/Elevator_pitch)"

**Comment by Mandur** [comment]
@roel4ez Did you want to work on this next sprint?
