### ISSUE TITLE
Device Provisioning Tool: NetID is documented as optional, but it is not

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#1083]
Remove NetID from AppSettings and it fails to build/run

**Comment by MaggieSalak** [comment]
@roel4ez I think this will be resolved with PR https://github.com/Azure/iotedge-lorawan-starterkit/pull/1376/files?short_path=6bddc69#diff-6bddc694cdb374dfe71eda366a2c11bb530a6332178ca79228e2b38f3063107d where it no longer says that `NetId` is optional, but that the default value set in `appsettings.json` can be optionally overridden by the user.
