### ISSUE TITLE
Harmonize Test's createuplinkUnconfirmed and createuplinkConfirmed  method

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1109]
The tests are using two methods to create unconfirmed and confirmed payload, this two methods are very similar and could by harmonized

**Comment by roel4ez** [comment]
@mandur please provide details and urgency

**Comment by Mandur** [comment]
This derives from a comment from @atifaziz. Imho out of scope for Jan. Will add description when I am back

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mandur** [comment]
After a look it seems this was already corrected, I will therefore close it @atifaziz, feel free to reopen if you disagree
