### ISSUE TITLE
Mac Commands piggybacked on the Fopts should not be ignored

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1120]
![image](https://user-images.githubusercontent.com/8555833/146569305-1b472841-c24c-473c-b571-812da192d20b.png)
Currently we only process mac commands in case they are in the main payload. We also need to process the mac commands piggybacked in the Fopts

**Comment by p-schuler** [comment]
@danigian - I think there are 2 issues here: the fopts support would be additional support (new feature), the key mismatch would be a bug. I wonder how that would work though? 

fyi @Mandur

**Comment by danigian** [comment]
I will tackle both issues in the same PR:
- Making sure that Mac Commands in FOpts are not ignored
- Making sure that when a FPort 0 is used, payload is decrypted with NwkSKey

**Comment by danigian** [comment]
I created #1203 for tracking the decryption issue
