### ISSUE TITLE
There is some SSL uncatched exceptions

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1135]
There are some SSL uncatched exception where certificates seems not to be valid, would be nice to catch those so that they also appear in the logs 
https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F0b439d3d-c7ae-4a59-8b19-87226095eba0%2FresourceGroups%2Florae2etests%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Florae2etestsinsight/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0utSE4tKMnMzytWqFEoz0gtSlUoycxNLS5JzC1QsLVVKMlPSSxJBQlpqBsZGBnqGhrpGhmGGJhbGRtZGRrpGRlYmplZmEapawIAq%252BZaC0oAAAA%253D

**Comment by danigian** [comment]
The exception you mentioned is being thrown by a piece of code we have no control onto (HttpsConnectionMiddleware of ASP.NET Core) therefore it's hard to catch this exception and log as the other ones.

Nevertheless, ideally these kind of warnings/errors coming from OpenSSL should be propagated in X509ChainStatusFlags and/or SslPolicyErrors that we can handle in ClientCertificateValidatorService.ValidateAsync

As of now, we are only logging the ChainStatus issues, without taking any concrete action on it and we are validating certificates based on their thumbprint.

We should increase the security of validation process by passing and trusting the root certificate (or full chain of trust) in LoRaWan Network Server Docker image.

I am going to close this issue and create a new one in the backlog (#1166)

fyi @bastbu
