### ISSUE TITLE
`DevAddr` is lost from responses provided by functions in `LoraKeysManagerFacade`

### ISSUE THREAD

**Issue by atifaziz** [Azure/iotedge-lorawan-starterkit#1149]
In PR #1073, `IoTHubDeviceInfo.DevAddr` was marked with `[JsonIgnore]`. This means that the property is never part of a JSON-serialized response from a function in `LoraKeysManagerFacade` that returns `IoTHubDeviceInfo`.

**Comment by p-schuler** [comment]
@atifaziz @bastbu - what endpoint are we specifically talking here and what calls?

**Comment by bastbu** [comment]
This affects every endpoint that uses the `LoraKeysManagerFacade.IoTHubDeviceInfo` for as the type for its result (which is the `GetDevice` and `GetDeviceByDevEUI` endpoint of the facade)
