### ISSUE TITLE
Empty field is used on the cache keys for deduplication causing more messages to potentially be detected as duplicates

### ISSUE THREAD

**Issue by spygi** [Azure/iotedge-lorawan-starterkit#1152]
## Current Behavior on Dev

Should fix ❌

When creating the cache keys, we are making use of the `RawPayload` field. The problem is that this is set only for the (old) `LoRaPayloadData` not the newer one `LoRaPayloadDataLns` which is actually used from the code. This means that we don't take into consideration the payload of the messages leading to more cache hits than what it should (false positives).

Since the default configuration is Deduplication None it means that we skip sending confirmation for more messages than what we should. The severity is worse with Deduplication drop because then we drop the messages immediately.

## Current behavior on latest release

Not affected ✔

According to Mik the last release happened on December 1. Checking what the code looked like on the next day a97a078d55d5e89eac59279c66731e21232761ba

- We are using `UpstreamDataFrameReader.Payload` which is populated (correctly) from the `Frmpayload`
- We are checking if the concentrator used is the same as on the previous message and if yes (which will be the case in the current deployment since they have only 1 concentrator : 1 gateway) we are *not* dropping messages (considered resubmissions)
  
## Current behavior on latest Github release

Not affected ✔

[According to the release list](https://github.com/Azure/iotedge-lorawan-starterkit/releases) the last one happened on November 15. The deduplication service was integrated after that in November 16 with this commit 853c2668e22cd07d02d67f9a90cacb0f3712a3c9.

**Comment by p-schuler** [comment]
@spygi - let us know if we need to triage this.

**Comment by spygi** [comment]
To sum up our discussion with @p-schuler :
- the reason why we had the payload there is to avoid collisions from the DevAddr (not unique)
- if we switch to using the DevEui we could completely drop the payload from the key.
