### ISSUE TITLE
Support AS923 in device provisioning CLI

### ISSUE THREAD

**Issue by bastbu** [Azure/iotedge-lorawan-starterkit#1199]
## Description

To configure concentrators for AS923 it would be helpful for the user to have support for AS923 in the device provisioning CLI. This would make sure that configuration is less error-prone and would make it easier to get started with this region.

## Acceptance criteria

- [ ] Device provisioning CLI supports AS923

**Comment by Mandur** [comment]
As per refinment, this would require some changes to the CLI to support dwell time & requires testing with the simulator. Postponed to Vnext

**Comment by Mandur** [comment]
Implemented in #1807 we default to set the dweel time to true as indicated by the spec
