### ISSUE TITLE
E2E CI should reset the redis cache between run

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1269]
Currently the E2E CI doesn't clean the cache between runs, we would want to perform such cleaning to avoid polluting another run with a previous information

**Comment by roel4ez** [comment]
Won't have time to add this to the 2.0 release. Here is what I found out though:

- The `flushall` and `flushdb` commands are only available on the redis-cli (https://phoenixnap.com/kb/clear-redis-cache)
- The `az redis` commands have no functionality for deleting keys (https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest)
- the redis-cli is *not* installed on github build server by default
- it is possible to connect to redis via `nc` or `telnet`, but couldn't get it wo work with Azure Redis (https://stackoverflow.com/questions/21795340/linux-install-redis-cli-only)


Maybe it can be done via the Azure Cloud Shell, or by installing redis-cli on-the-fly and then executing the commands.
Or, extend the Function with a `ResetCache` api, and use that.
