### ISSUE TITLE
(Some) MAC commands are sent downstream with reversed bytes

### ISSUE THREAD

**Issue by atifaziz** [Azure/iotedge-lorawan-starterkit#1281]
## Expected Behavior

The `ABP_Unconfirmed_Sends_Valid_Mac_Commands_In_Fopts_And_Reply_In_Fopts` test in `ProcessingTests` sends a `LinkCheckReq` MAC command via `LinkCheckRequest` and expects a `LinkCheckAns` via `LinkCheckAnswer`. The downstream message has 21 bytes laid out as follows:

    [0] = 96
    [1] = 1 
    [2] = 0 
    [3] = 0 
    [4] = 2 
    [5] = 3 
    [6] = 1 
    [7] = 0 
    [8] = 1 
    [9] = 15
    [10] = 2 
    [11] = 1 
    [12] = 42
    [13] = 154
    [14] = 243
    [15] = 239
    [16] = 125
    [17] = 85
    [18] = 216
    [19] = 5 
    [20] = 188

At offset 5, the `FOptsLen` correctly indicates 3 bytes of `FOpts`, which is supposed to be the MAC command in the offsets range 8..10 (inclusive). At offset 8, the command identifier should be 2 for `LinkCheckAns`.

## Current Behavior

The command identifier is incorrect and instead can be found at offset 10. The MAC commands bytes seemed to be written in the reverse order.

The test passes nonetheless because the `LinkCheckAnswer` constructor used in the test for assertion interprets the bytes in the reverse order:

https://github.com/Azure/iotedge-lorawan-starterkit/blob/f19bd7b5d8c060d77d9a30f938276de561f2cbca/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/LinkCheckAnswer.cs#L38-L43

## Steps to Reproduce

1. Put a breakpoint on line 306 of `ProcessingTests`:
   https://github.com/Azure/iotedge-lorawan-starterkit/blob/f19bd7b5d8c060d77d9a30f938276de561f2cbca/Tests/Integration/ProcessingTests.cs#L306
1. Run the `ABP_Unconfirmed_Sends_Valid_Mac_Commands_In_Fopts_And_Reply_In_Fopts` test in `ProcessingTests`.
1. Examine the contents of `request.ResponseDownlink.Data` memory when the breakpoint hits. Note that bytes from offset 8 to 10 are inverted.

**Comment by danigian** [comment]
After investigating this, we found out that the reason why the Mac Commands are serialized "reversed" is because we are assuming that these will be always sent in the FRMPayload (whose bytes are being reverted in the LoRaPayloadData constructor)

Ideally all MacCommand "ToBytes" overloads should always return CID first and then any other eventual octet, this will require some changes in the LoRaPayloadData constructor too
