### ISSUE TITLE
LNS incorrectly rejects data frames (`updf`) where `FPort` = -1

### ISSUE THREAD

**Issue by atifaziz** [Azure/iotedge-lorawan-starterkit#1282]
## Expected Behavior

Expected LNS to handle data frames where `FPort` is -1 (meaning missing), as per the spec:

    {
        "msgtype"   : "updf",
        "MHdr"      : UINT,
        "DevAddr"   : INT32,
        "FCtrl"     : UINT,
        "FCnt",     : UINT,
        "FOpts"     : "HEX",
        "FPort"     : INT(-1..255),
        "FRMPayload": "HEX",
        "MIC"       : INT32,
        ..
    }

## Current Behavior

The LNS rejects the frame as being invalid with the message: _Received unexpected 'jreq' message: …."_

The problem seems to stem from the fact that the `Port` is read as an unsigned byte (see line 98):

https://github.com/Azure/iotedge-lorawan-starterkit/blob/f19bd7b5d8c060d77d9a30f938276de561f2cbca/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/JsonHandlers/LnsData.cs#L91-L106

**Comment by danigian** [comment]
As additional detail, this scenario might only happen if FRMPayload is empty. FPort MUST be specified if FRMPayload is filled instead
![image](https://user-images.githubusercontent.com/1955514/149526516-4ce397ee-f3bf-4913-9900-003fdf0e1874.png)

**Comment by atifaziz** [comment]
@danigian Right, so either:

- `FPort` is -1 and `FRMPayload` an empty string
- `FPort` is a byte (0…255) and `FRMPayload` a non-empty string whose length is always even (hexadecimal encoding so always two characters per byte)
