### ISSUE TITLE
LMIC support for class C devices

### ISSUE THREAD

**Issue by fbeltrao** [Azure/iotedge-lorawan-starterkit#131]
**Is your feature request related to a problem? Please describe.**
In order to facilitate testing it would be useful to add class C support for Heltec device. Currently we are running the version available here: https://github.com/ronniesa/ArduinoESP32LoRaWAN

**Describe the solution you'd like**
Add possibility to switch between class A and C based on long clicks of the PRG button.
- 1x long PRG click: switch between confirmed and unconfirmed
- 2x long PRG click: switch between class A and C type. In class C mode, display the incoming message in the display

**Comment by Mandur** [comment]
I will close this one as LMIC support is not a priority at the moment
