### ISSUE TITLE
`ConcentratorCredentialsFunction`, `ConcentratorFirmwareFunction` shouldn't return 422

### ISSUE THREAD

**Issue by atifaziz** [Azure/iotedge-lorawan-starterkit#1329]
## Expected Behavior

Expected `ConcentratorCredentialsFunction` and `ConcentratorFirmwareFunction` to return 500 when unable to read CUPS information from the twin or if the information is incorrect.

## Current Behavior

The functions returns a [422 (Unprocessable Entity)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422). MDN clearly warns that this is not designed for server problems because it requires the client to modify the request before re-submitting:

> The HyperText Transfer Protocol (HTTP) **422 Unprocessable Entity** response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.
>
> **Warning:** The client should not repeat this request without modification.

422 originated in WebDAV, [which says](https://datatracker.ietf.org/doc/html/rfc4918#section-11.2):

> The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a    415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions.  For example, this error condition may occur if an XML request body contains well-formed (i.e., syntactically correct), but semantically erroneous, XML instructions.

So even in WebDAV, it's referring to the instructions in the _request entity_, not the _response entity_.

**Comment by bastbu** [comment]
Bug also applies `ConcentratorCredentialFunction`
