### ISSUE TITLE
adf apply waiting for creation of Template Deployment when deploying ARM Template

### ISSUE THREAD

**Issue by sahil-shethiya-kr** [Azure/iotedge-lorawan-starterkit#1330]
waiting for creation of Template Deployment "adfdiv011outtemptdeploy" (Resource Group "rg-posh-deva52-eastus2"): Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Missing parameter definition for content\",\r\n    \"target\": \"Pipeline/Out_011\",\r\n    \"details\": null\r\n  }\r\n}"}]
│ 
│   with azurerm_resource_group_template_deployment.adfdivoutbound["011"],
│   on main.tf line 151, in resource "azurerm_resource_group_template_deployment" "adfdivoutbound":
│  151: resource "azurerm_resource_group_template_deployment" "adfdivoutbound" {

│ Error: waiting for creation of Template Deployment "adfdiv014outtemptdeploy" (Resource Group "rg-posh-deva52-eastus2"): Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Missing parameter definition for content\",\r\n    \"target\": \"Pipeline/Out_014\",\r\n    \"details\": null\r\n  }\r\n}"}]
│ 
│   with azurerm_resource_group_template_deployment.adfdivoutbound["014"],
│   on main.tf line 151, in resource "azurerm_resource_group_template_deployment" "adfdivoutbound":
│  151: resource "azurerm_resource_group_template_deployment" "adfdivoutbound" {

**Comment by roel4ez** [comment]
@sahil-shethiya-kr was this created on the wrong repository by accident? It seems to be a Terraform log, but it is not something we are using in our repo.
