### ISSUE TITLE
Create the Application Insight "Workspace base"

### ISSUE THREAD

**Issue by kbeaugrand** [Azure/iotedge-lorawan-starterkit#1454]
**Is your feature request related to a problem? Please describe.**
The classic Application insights is deprecated. 
![image](https://user-images.githubusercontent.com/9513635/152157913-13e0a3bc-b4af-485e-bce9-14061e913fe8.png)

**Describe the solution you'd like**
On the template, create a Workspace based Application insights instance.

Add the resource property ``WorkspaceResourceId`` on the template: 
```
{
            "type": "Microsoft.Insights/components",
            "kind": "web",
            "name": "[variables('appInsightName')]",
            "apiVersion": "2015-05-01",
            "location": "[resourceGroup().location]",
            "scale": null,
            "properties": {
                "ApplicationId": "[variables('appInsightName')]",
                "WorkspaceResourceId": "[resourceId('Microsoft.OperationalInsights/workspaces/', variables('logAnalyticsName'))]"
            },
            "dependsOn": [
                "[resourceId('Microsoft.OperationalInsights/workspaces/', variables('logAnalyticsName'))]",
            ]
        },
```

**Describe alternatives you've considered**
Manual migration is available on the portal: 

![image](https://user-images.githubusercontent.com/9513635/152158221-d4b36e28-f3f9-4192-bb15-0cae9a513163.png)

**Additional context**
See [https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource)

**Comment by bastbu** [comment]
Thanks @kbeaugrand for reporting this. The changes are now in `dev` and will be released with the next version of the release.

**Comment by kbeaugrand** [comment]
Excellent! Thank you @bastbu
