### ISSUE TITLE
Consider using Azure Sphere for the Starter kit

### ISSUE THREAD

**Issue by spygi** [Azure/iotedge-lorawan-starterkit#1455]
[Azure Sphere](https://azure.microsoft.com/en-us/services/azure-sphere/) allows a secure way to connect MCU devices to the cloud. Main advantages are regular OS updates as well as concentrator app updates and multiple security features. We should investigate whether this is something that could be an option for the Starter Kit to integrate with.

- [x] #1456

**Comment by Mandur** [comment]
Closing as the investigation is completed
