### ISSUE TITLE
Revisit background cache refresh

### ISSUE THREAD

**Issue by spygi** [Azure/iotedge-lorawan-starterkit#1505]
When we create the (singleton) instance of the NetworkServer.LoRaDeviceCache, we start a background periodical task to ensure the device twins for all the devices that connected to that LNS are kept fresh. We check every 10 minutes if the twin was refreshed in the last 2 days and eventually drop it from the cache if not seen in 10 days. 

In the context of the connection ping-pong we decided for the first version to not check the Function and accept a potential connection switch every 2 days. Here we want to solve this in a better way. Note that the solution needs to be evaluated based also on resolution of #1499 

## Acceptance criteria
- Evaluate different options on whether and how we need to address this, see relevant section in ADR
- Implement changes

**Comment by p-schuler** [comment]
We will keep refreshing the information in the background. There is no ownership change when we do this and we can guarantee that no other operations on the connection are being performed with the new design. The only problem remaining is the state change of the LoRaDevice while being in use.
