### ISSUE TITLE
[Story] Upgrade Universal Decoder sample to use latest Node LTS

### ISSUE THREAD

**Issue by atifaziz** [Azure/iotedge-lorawan-starterkit#1612]
## Description

The Universal Decoder sample is pinned to Node v14 in the Docker files, which will reach end-of-life in about a year. It should be updated to use the latest LTS sometime before then.

## Acceptance criteria

- [ ] Universal Decoder is updated to use latest LTS of Node

**Comment by atifaziz** [comment]
Re-opening because this was accidentally closed by incorrect association with PR #1613.

**Comment by Mandur** [comment]
As the universal decoder was removed I close the issue
