### ISSUE TITLE
Universal Decoder is missing some LoRaWAN devices

### ISSUE THREAD

**Issue by danigian** [Azure/iotedge-lorawan-starterkit#1833]
## Expected Behavior
Universal decoder pipeline should succeed and lw001-bg related tests should pass

## Current Behavior
The pipeline fails because a decoder is not found (lw001-bg)
A recent change in [Device Repository for LoRaWAN](https://github.com/TheThingsNetwork/lorawan-devices/pull/495) made the lw001-bg move from decodeUplink function to a "Decoder" function that we are currently not able to parse and modify to make it usable in the universal decoder.

**Comment by Mandur** [comment]
As the Universal decoder was removed I close this issue
