### ISSUE TITLE
LNS Discovery Tests are broken

### ISSUE THREAD

**Issue by danigian** [Azure/iotedge-lorawan-starterkit#1866]
#1795 broke LNS Discovery Test by introducing a dependency on environment variables that are only available in the deployed web app for Facade Function.

# Acceptance criteria
- [ ] E2E should be independent from those function app related environment variables
- [ ] Tests should work again

**Comment by Mandur** [comment]
Discovery tests are working again, thank you!

**Comment by Mandur** [comment]
reopened as it seems not to be working
