### ISSUE TITLE
Migrate Infrastructure to Bicep

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1884]
## Description

We want to migrate the LoRaWan Starterkit to use bicep as IaC language in order to benefit from the latest language features and remove unneeded endpoint.

## Acceptance criteria

- [x] #1897
- [x] #1896
- [x] #1920
- [x] #1921
- [x] #1893

## Resources

- [Spike done at OCW22 to experiment with bicep](https://github.com/Azure/iotedge-lorawan-starterkit/tree/feature/add-bicep-infra/Template)

## Out of scope

- Any Automated Infrastructure deployment. The infrastructure will be deployed manually

**Comment by kbeaugrand** [comment]
Hi, question on that topic, will the bicep template be stored in a public registry ?

**Comment by Mandur** [comment]
Hello @kbeaugrand,

This is currently not being planned but out of curiosity why would it interest you? Is there something with the portal?

**Comment by kbeaugrand** [comment]
Yes, we are thinking about providing bicep templates for the portal. But we'd like to still use the starterkit template dependency. 
But it seems that template dependency inside bicep needs to use templates that are published in a registry...

**Comment by Mandur** [comment]
As discussed the compiled bicep will be published from now on as part of our releases
