### ISSUE TITLE
The Docker can not work in US915

### ISSUE THREAD

**Issue by RAKWireless** [Azure/iotedge-lorawan-starterkit#190]
Hi,
I'm testing the IoT edge Docker on RAK833 + RPi.
It works fine in EU868, but it can not work in US915.
Then i compare the central frequency of this Docker with TTN, the result is shown in the following picture:
![image](https://user-images.githubusercontent.com/23307155/57377141-4966f380-71d4-11e9-82f7-d9d1a3c3be3e.png)

As you see, they are different.
Then, i modify the Azure central frequency from "902700000" to "904300000" manually, it works fine! 
Why? Is there a bug in the Docker?

**Comment by Mandur** [comment]
Hello @RAKWireless,

Thank you very much for your post and tests with our solution. 
The US915 LoRa spectrum is much wider than the EU868 and offer possibilities to choose different channel frequencies for the network frequency plan. TTN choose to implement a frequency plan starting from higher up in the frequencies, whereas our configuration takes the [default Semtech packet forwarder US915 settings](https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/cfg/global_conf.json.US902.basic). 
If you use end devices built for TTN or another operator with specific frequency plans, the packet forwarder frequency plan will need to be adjusted in order for your gateway to receive messages correctly as you described above.
We do not plan to propose any other frequency plan than default as we would like to avoid interfering with other provider's frequencies if this can be avoided.

**Comment by RAKWireless** [comment]
OK, i've got it, thank you!
