### ISSUE TITLE
Beaconing is tested for European frequency with custom GPS information

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1909]

**Comment by Mandur** [comment]
We were not able to make the custom GPS information work, the custom coordinates gets ingested, but not propagated on the device.

**Comment by noraabiakar** [comment]
Custom GPS data being ingested: 
![image](https://user-images.githubusercontent.com/18661075/198979432-26291a7d-3cca-4096-8182-7d204bd70442.png)

Different coordinates displayed on the device:
![image](https://user-images.githubusercontent.com/18661075/198982559-878ada46-efe4-47bd-9045-f3c6ba3f2404.png)

**Comment by Mandur** [comment]
Closed as seems to be a Basics station issue we will reopen if needed
