### ISSUE TITLE
Australian frequencies should be unit tested

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1911]
The test data is here: https://github.com/Azure/iotedge-lorawan-starterkit/compare/dev...feature/add-au-2#diff-0184dc9f6055a86a457f6059c76519fa52ade8f4bc2cecd3952419be5378e896

the test code is here https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/Tests/Unit/LoRaTools/RegionTest.cs

**Comment by ouphi** [comment]
Tests are passing.
