### ISSUE TITLE
Australian frequencies should be manually tested

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1912]
Use the code there : 
https://azure.github.io/iotedge-lorawan-starterkit/2.2.0/samples/arduino/ to test for ABP OTAAs. the branch should already have Australian versions

**Comment by ouphi** [comment]
ABP works:
<img width="324" alt="Screenshot 2022-10-26 at 11 16 26" src="https://user-images.githubusercontent.com/17216799/198019971-84c1faf5-beaf-4f5f-b2c9-1460d59789e7.png">

**Comment by ouphi** [comment]
C2D works:
<img width="377" alt="Screenshot 2022-10-26 at 13 11 15" src="https://user-images.githubusercontent.com/17216799/198020038-d5132586-7a88-4a1d-a8fd-036c4a886e83.png">

**Comment by ouphi** [comment]
OTAA works:
<img width="385" alt="Screenshot 2022-10-26 at 13 57 27" src="https://user-images.githubusercontent.com/17216799/198020274-0301c99e-601a-417f-9a2d-d0c089652c84.png">
