### ISSUE TITLE
Remove the Facade auth code from the logs

### ISSUE THREAD

**Issue by kbeaugrand** [Azure/iotedge-lorawan-starterkit#1916]
## Expected Behavior

Credentials should be obfuscated event in logs.

## Current Behavior

On the ``LoRaWANNetworkSrvModule`` we can see in clear the Facade auth code

<img width="731" alt="image" src="https://user-images.githubusercontent.com/9513635/197710273-58e97793-308a-4b31-993b-808c4258bde0.png">

## Steps to Reproduce

1. Go the the LoRaWANNetworkSrvModule logs

### Device (Host) Operating System

N/A 

### Architecture

N/A

### Container Operating System

Linux containers 

### LoRaWAN Module Version

2.2.0

#### Docker

N/A

**Comment by Mandur** [comment]
Hello @kbeaugrand 

Thank you for reporting this, we will have a look

**Comment by Mandur** [comment]
By adding the environment variable 
        "Logging:LogLevel:System": "None"
should disable this behavior, we will move into integrating this in upstream.

**Comment by kbeaugrand** [comment]
Fine, that works, but we do not have any logs about query executed on the Facade. 
Not a big deal
