### ISSUE TITLE
Document twin settings for Class B beaconing

### ISSUE THREAD

**Issue by noraabiakar** [Azure/iotedge-lorawan-starterkit#1959]
Document on [this page](https://azure.github.io/iotedge-lorawan-starterkit/2.2.0/user-guide/station-device-provisioning/#manual-configuration) what are the optional device twins needed to activate the Class B beaconing

**Comment by danigian** [comment]
Can this be closed, @noraabiakar?

**Comment by Mandur** [comment]
Yes
