### ISSUE TITLE
Release pipeline: Azure Functions zip improperly created

### ISSUE THREAD

**Issue by danigian** [Azure/iotedge-lorawan-starterkit#1984]
## Expected Behavior
The Azure Functions zip should have, in its root, the content of the folder specified [in this line](https://github.com/Azure/iotedge-lorawan-starterkit/blob/f82dcbd3d015ecd40b238e7dabc000257f495f2e/.github/workflows/create_release.yaml#L117) and not the full folder structure.

See comparison below
![image](https://user-images.githubusercontent.com/1955514/202679418-bbba5b25-f89b-4ad7-9f0c-df929a8ec994.png)

Azure Functions zip for release 2.2.1 is now manually fixed by me. Pipeline should be fixed before next release

**Comment by Mandur** [comment]
Fixed by https://github.com/Azure/iotedge-lorawan-starterkit/pull/1992
