### ISSUE TITLE
Deployment is not idempotent when the deployDevice parameter is enabled

### ISSUE THREAD

**Issue by hocinehacherouf** [Azure/iotedge-lorawan-starterkit#2061]
## Expected Behavior

When the `deployDevice` parameter is set to true, the deployment of  iotedge-lorawan-starterkit must be idempotent. Each deployment (with the deployDevice parameter equal to true) should:

- Create the device if it doesn't exist
- Update the device if its configuration is not up to date
- Ignore the lora device if it exists and its configuration it up to date

## Current Behavior

With the `deployDevice` parameter set to true

- The first deployment from scratch was successful.
- The second and subsequent deployments (with the same settings) fails at the `createIothubDevices` step.

https://github.com/Azure/iotedge-lorawan-starterkit/blob/267d00cb8861dec87c504f06b3874330322f6011/TemplateBicep/devices.bicep#L31-L33

The output error message:

```json
{
    "status": "failed",
    "error": {
        "code": "DeploymentScriptError",
        "message": "The provided script failed without returning any errors. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information."
    }
}
```

## Steps to Reproduce

1. Go to [Quick Start guide](https://azure.github.io/iotedge-lorawan-starterkit/dev/quickstart/?h=discovery#step-by-step-instructions) and press the 'Deploy to Azure' button.
2. In the 'Custom Deployment' page that opens
    - Fill out all required fields
    - Choose 'true' in the 'Deploy Device' dropdown.
3. Review + Create the deployment.
4. Wait until the end of the deployment
5. Create a new deployment with the same parameters

**Comment by Mandur** [comment]
Good point, we will provide a fix
