### ISSUE TITLE
Question:  Support for Azure IoT Edge 1.0.7?

### ISSUE THREAD

**Issue by gerfen** [Azure/iotedge-lorawan-starterkit#210]
I'm curious when there will be a release which as been tested with azureiotedge-agent:1.0.7 and azureiotedge-hub:1.0.7?

I was force to use these on my test gateway in order to send direct messages to class C devices.  I will soon need to roll out class C devices to a production gateway but I am hesitant to do so until there is a supported release.

**Comment by ronniesa** [comment]
We have released 1.0.1 two weeks ago unfortunately due to time constrain on testing still using 1.0.6. 
We plan to do the next release in a couple of weeks that will move Edge to 1.0.7

**Comment by gerfen** [comment]
@ronniesa Thanks for the info!
