### ISSUE TITLE
No matching manifest for linux/arm/v7

### ISSUE THREAD

**Issue by Terrence77** [Azure/iotedge-lorawan-starterkit#2123]
Azure IoT Edge LoRaWAN Starter Kit

I have installing AzureIotEdge to my Raspberry Pi with the Seeed Stuio Wm1002 lora concentrator.

I noticed in My IOTHub / Devices / MyGateway that LoRaWanNetworkSrvModule and LoRaBasicsStationModule were showing a runtime status as Error.

I went to my gateway and issued this command to look at the logs and found this error.

sudo iotedge system logs

2024-01-17T01:50:03Z [WARN] - Could not pull image loraedge/lorabasicsstationmodule:2.2.2
2024-01-17T01:50:03Z [WARN] - caused by: no matching manifest for linux/arm/v7 in the manifest list entries

No manifest for linux/arm/v7  ??
Doing research I noticed on this website that the linux/arm/v7 2.2.2 file does exist.
https://hub.docker.com/r/loraedge/lorabasicsstationmodule/tags

Ideas on solving this issue?

Thank you.

**Comment by Terrence77** [comment]
I know this probably is not the place for tech support, but I have searched the net and can't find any forum answering questions about this great project.

Suggestions?

**Comment by kbeaugrand** [comment]
@Terrence77, is this a transient error ? 

As far I know by looking in the manifest, there is a tag for  linux/arm/v7: 
![image](https://github.com/Azure/iotedge-lorawan-starterkit/assets/9513635/a5602163-a406-49ab-af78-316f47dfdcda)

Otherwise, you can manually specify to download the required image for testing purpose: loraedge/lorabasicsstationmodule:2.2.2-arm32v7

**Comment by Terrence77** [comment]
@kbeaugrand Thank you for your reply.

Yes, that is what I was trying to get across in my post, that the file DOES exist.
>>Doing research I noticed on this website that the linux/arm/v7 2.2.2 file does exist.
>>https://hub.docker.com/r/loraedge/lorabasicsstationmodule/tags


>>is this a transient error 

Well I am seeing the error in the Azure portal.
![Screenshot 2024-01-23 080748](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/7d17d871-dd9f-4e4f-8fa8-85571db3ead2)


>>Otherwise, you can manually specify to download the required image for testing purpose: loraedge/lorabasicsstationmodule:2.2.2-arm32v7

I "think" I tried that but was not successful.

I am new to containers so I am sure I mangled my syntax.

**Comment by Terrence77** [comment]
@kbeaugrand 

>>Otherwise, you can manually specify to download the required image for testing purpose: loraedge/lorabasicsstationmodule:2.2.2-arm32v7

Can I specify this in the Azure Portal, or do I need to do it in Bash on the gateway?

Thanks.

**Comment by kbeaugrand** [comment]
> @kbeaugrand 
> 
> 
> 
> >>Otherwise, you can manually specify to download the required image for testing purpose: loraedge/lorabasicsstationmodule:2.2.2-arm32v7
> 
> 
> 
> Can I specify this in the Azure Portal, or do I need to do it in Bash on the gateway?
> 
> 
> 
> Thanks.

Please share us the configuration you are using in the portal for the module.

**Comment by Terrence77** [comment]
Thank you for your continued support on my issue.
I am very excited to get this working for my Lora IOT network.

I have been following these instructions.
https://azure.github.io/iotedge-lorawan-starterkit/dev/quickstart/

Here is the hardware config and setup.

`Rasp Pi 2B
Pi OS Lite 32bit Debian Bulllseye
Seeed WM1302

sudo raspi-config
Endable SPI interface
Endable IC2 interface

sudo apt update
sudo apt install -y git
cd ~
git clone https://github.com/Lora-net/sx1302_hal
cd ~/sx1302_hal
make


curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
sudo apt-get install ./packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install moby-engine
sudo curl -L https://github.com/Azure/azure-iotedge/releases/download/1.2.5/aziot-identity-service_1.2.4-1_debian11_armhf.deb -o aziot-identity-service.deb && sudo apt-get install ./aziot-identity-service.deb
sudo curl -L https://github.com/Azure/azure-iotedge/releases/download/1.2.5/aziot-edge_1.2.5-1_debian11_armhf.deb -o aziot-edge.deb && sudo apt-get install ./aziot-edge.deb


pi@raspberrypi:~ $ sudo iotedge system status
System services:
    aziot-edged             Running
    aziot-identityd         Running
    aziot-keyd              Running
    aziot-certd             Running
    aziot-tpmd              Ready
`

**Comment by Terrence77** [comment]
![Screenshot 2024-01-24 092945](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/eccacadd-6a4b-43cd-9491-229a5c8ef91f)


![Screenshot 2024-01-24 093045](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/a89874bf-87a9-4279-b5f4-7a491999e9dc)


![Screenshot 2024-01-24 093106](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/fc226062-b806-4e4b-acde-9080f0794172)


![Screenshot 2024-01-24 093118](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/1413c71f-b047-4f30-85ea-703799c47efe)


![Screenshot 2024-01-24 093141](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/ab8142c3-66d3-4fbf-bc21-a9abe5729c17)


![Screenshot 2024-01-24 093151](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/ed90894a-9c13-4964-b09a-9942b11114ec)


![Screenshot 2024-01-24 093203](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/374b1c2f-ae05-4bf6-9645-89a398125d75)

**Comment by Terrence77** [comment]
The script that ran when I clicked "Deploy to Azure" setup the devices in my IOTHub.
I note that one of the devices is a concentrator (my Seeed WM1302?).
The device twin shows it being a 1301, NOT a 1302.

![Screenshot 2024-01-24 162801](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/b7baa9d5-2517-42c7-ae06-8be1cf9cab6c)


![Screenshot 2024-01-24 162854](https://github.com/Azure/iotedge-lorawan-starterkit/assets/46733900/daa110e9-947a-4d5b-a4f6-52c4f07f3dc9)

**Comment by Mandur** [comment]
Apologies for not seeing the issue earlier, are you still trying to fix it?

Did you try to run "docker pull loraedge/lorabasicsstationmodule:2.2.2-arm32v7" on your target device?

**Comment by Terrence77** [comment]
No, I bailed on the project.

**Comment by Mandur** [comment]
Understood, sorry we did not see the request earlier, have a great weekend!
