### ISSUE TITLE
Use NetworkServer Module with external gateway?

### ISSUE THREAD

**Issue by roman-ruthofer** [Azure/iotedge-lorawan-starterkit#2127]
**Description**
We are using the following indoor lora gateway
https://www.thermokon.de/direct/en-gb/categories/gateway-lrw-indoor-femto

Is there any way to use the NetworkServer Module with such external gateways? It seems like the gateway is using UDP and the NetworkServer Module only exports TCP Ports.

**Comment by kbeaugrand** [comment]
Hi, 

Network server supports Lora Basic station connectivity. 

It seems that regarding the datasheet of your gateway that is also supported. 

I suggest you to look at this side.

**Comment by roman-ruthofer** [comment]
> Hi,
> 
> Network server supports Lora Basic station connectivity.
> 
> It seems that regarding the datasheet of your gateway that is also supported.
> 
> I suggest you to look at this side.

I'll have a look. Thanks!

**Comment by roman-ruthofer** [comment]
@kbeaugrand I'm still confused if I need an edge device with "Lora Board" or if I can run it on any device running IoT Edge Runtime. I can't find a clear answer to this in the documentation.
And my BaseStation log shows the error `[HAL:ERRO] [lgw_start:742] FAIL TO CONNECT BOARD`.

**Comment by kbeaugrand** [comment]
NetworkServer can run on every machine where iotedge runtime works... 
it doesn't require a LoRaWan antenna
