### ISSUE TITLE
Question:  Docker Version?

### ISSUE THREAD

**Issue by gerfen** [Azure/iotedge-lorawan-starterkit#218]
I'm getting ready to install a fresh install of 1.0.2 to a new instance of Azure IoT Hub.  I currently have Docker Version 18.03.0-ce-win59 (16762) installed on my dev box.  What is the recommended Docker version for the latest code?

Thanks!

**Comment by Mandur** [comment]
As we are based on the IoT Edge Runtime and perform all our tests against it, I would say the docker recommended version is the one that IoT Edge is using.

**Comment by Mandur** [comment]
I will close the issues, please feel free to reopen if you still have follow up questions.
