### ISSUE TITLE
[Spike]Investigate deployment simplification

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#242]
Due to recent ARM improvement, we might be able to decommission the provisioning part of the function

**Comment by Mandur** [comment]
[This]((https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template?tabs=CLI)) could be done to remove the dependency on the Azure function for the initial solution deployment. That would require some time, to be properly set up and tested. I will move the implementation to the next milestone

**Comment by danigian** [comment]
@Mandur is this superseeded by #1884?

**Comment by Mandur** [comment]
Yes good catch, closing
