### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by levalencia** [Azure/iotedge-lorawan-starterkit#251]
In the developer guidance page:
https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/Docs/devguide.md

There is a broken link:, in the text: Build and deploy the Azure function.
The Azure Functions Link is broken

**Comment by Mandur** [comment]
Thank you for reporting, I will ammend

**Comment by Mandur** [comment]
It was fixed in #254. Thank you very much @levalencia for bringing this up.
