### ISSUE TITLE
The remote version "~3" for function app does not match your local version "~2"

### ISSUE THREAD

**Issue by levalencia** [Azure/iotedge-lorawan-starterkit#252]
I created the function app manually in Azure, It ask a runtime, I selected .net Core and latest version 3.1

From VS Code I tried to deploy but I get this warning above.

I didnt see an option in Azure Portal to downgrade or create a new function app with version 2 runtime.

Should I deploy anyways?, or am I missing something here?

[Window Title]
Visual Studio Code

[Content]
The remote version "~3" for function app "xxxx" does not match your local version "~2".

[Deploy Anyway] [Learn more] [Cancel]

**Comment by Mandur** [comment]
The current master branch is still on .NET core 2.1. A new release in the next days will upgrade to .NET 3.1. If you want to solve your current issue and deploy for .net 2.1 you should go in the configuration section of your Azure functions and set the variable FUNCTIONS_EXTENSION_VERSION to ~2, then restart the Azure function and this should work

**Comment by levalencia** [comment]
Thank you
