### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by levalencia** [Azure/iotedge-lorawan-starterkit#267]
On this page:

https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/Docs/devguide.md#use-a-proxy-server-to-connect-your-concentrator-to-azure

On this section:
Provision LoRa leaf device
The sample code used in this example is based on Seeeduino LoRaWAN with a Grove - Temperature Sensor. It sends every 30 seconds its current temperature reading and prints out a Cloud-2-Device message if one is transmitted in its receive window.

The sample code  points to 404

**Comment by Mandur** [comment]
Correct link is [that](https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/Arduino/EU/TemperatureOtaaLora/TemperatureOtaaLora.ino)
