### ISSUE TITLE
SPI - how does it fit into the architecture

### ISSUE THREAD

**Issue by donniekerr** [Azure/iotedge-lorawan-starterkit#275]
I'm not an electronics guy.  I think I understand how it works on the device to chain slaves, etc. 
https://www.makeuseof.com/tag/enable-spi-i2c-raspberry-pi/
Given that, I can understand how many sensors can connect to a Lora Module chip using it before sending the data to the Gateway.

My question is, how does it fit into the gateway side architecture?  @gerfen gave me instructions on how to add the files for  it to my AAEON gateway.  But I'm trying to get educated on how it is used in the data flow through the gateway. Does it interface with the packet forwarder? What is the role of SPI on the gateway?

**Comment by donniekerr** [comment]
I think i get it now.  
SPI, running on each Lora Node integrates data from multiple sensors. 
SPI, running on the Gateway integrates data from multiple Lora nodes. 

Since the Concentrator is software in the edge module, it isn't clear to me how it uses SPI though.

**Comment by gerfen** [comment]
Are you trying to determine how many devices can be supported by your gateway?

**Comment by gerfen** [comment]
My understanding is SPI is used by the OS to "talk" to the concentrator hardware - I believe that AAEON uses the Semtech SX1301 concentrator.  This link is helpful.... https://static6.arrow.com/aropdfconversion/d45a99f75ae1eaf8862dd031e5016b050158f561/sx1301.pdf

**Comment by donniekerr** [comment]
Ah ha! That's the piece I was missing.  I see the reference to SX1301 here too
https://github.com/Lora-net/packet_forwarder/tree/master/lora_pkt_fwd#lora-gateway-packet-forwarder 

Makes sense now that the hardware uses the SPI bus to move the data to the software in the packet forwarder and then on to the network server. 

Thanks!

**Comment by ronniesa** [comment]
SPI is a bus like PCI on embedded systems. The radio HW and firmware (Semtech chip) talk over the SPI bus with the PacketForwarder that he then format the packet and forward to a UDP endpoint where our NetworkServer module picks it up and do all the processing including impersonating the device against IoT Hub, decrypt, ev. decode and send the message upstream

**Comment by donniekerr** [comment]
Thank you @ronniesa .  Might be good to add the Concentrator Hw and SPI to this diagram https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/Docs/Pictures/EdgeArchitecture.png .  I think I was just trying to figure out what was happening inside the packet forwarder box. i.e. was it all software or some hardware.  Now it is clear to me.  Appreciate the education guys!
