### ISSUE TITLE
Periodical loss of connection on devices (+- 24H)

### ISSUE THREAD

**Issue by maxstefaniv** [Azure/iotedge-lorawan-starterkit#292]
## Expected Behavior
Devices will report telemetry non stop, reaching IoT Hub with no issues.

## Current Behavior
After Set Up devices Reported properly for around 24 hours after that started displaying:
`could not send message to IoTHub/Edge with error: The operation timed out.`
Unless iotEdge is rebooted, all devices will report the same message.

## Steps to Reproduce

1. Deploy the project as it is (gateway device AIOT-ILRA01) (Devices ELSYS Co2 and Netvox R311W)
2. Add additional decoder (should not be an issue as this module only decodes the message coming from the device as telemetry.)
3. Wait 24h

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
amd64

### LoRaWAN Module Version
```
LoRaWanNetworkSrvModule  running          Up 2 hours       loraedge/lorawannetworksrvmodule:1.0.5
LoRaWanPktFwdModule      running          Up 2 hours       loraedge/lorawanpktfwdmodule:1.0.5
edgeAgent                running          Up 2 hours       mcr.microsoft.com/azureiotedge-agent:1.0.9.5
edgeHub                  running          Up 2 hours       mcr.microsoft.com/azureiotedge-hub:1.0.9.5
```

## Logs
Attached support_bundle.zip
[support_bundle.zip](https://github.com/Azure/iotedge-lorawan-starterkit/files/6451463/support_bundle.zip)

## Story description:
Starting with the LoRaWAN Gateway (AAEON AIOT-ILRA01), we deployed default modules from Microsoft Git and modified one additional module “DecoderValueSensor” adding logic to decode telemetry and deployed it on the Edge Device.
Afterwards, we enrolled a total of 24 multi-sensors, making sure they are sending telemetry that is reaching the IoT Hub, and stored messages are correctly decoded. Everything was fine.
We left the set up connected both to a network and to a power source. The following day, we connected to the Edge Device through SSH connection and noticed a series of error messages:
`could not retrieve device twin with error: The operation timed out.`
In response to this error, we restarted the Edge Device `sudo systemctl restart iotedge`, after which all modules restarted and, through checking the logs, error messages no longer appeared, so everything went back to normal.

 1. Can you propose any other solutions that will allow us to detect this anomaly ASAP?
 2. Is this behavior normal, have you encountered it before?

**Comment by ronniesa** [comment]
@maxstefaniv does this happens only after deploying a new decoder or every time after 24h?

**Comment by maxstefaniv** [comment]
@Mandur Hello, yeah "ENABLE_GATEWAY to false" was already set otherwise I was getting an error, that was a fix I already scaned from existing issues.

@ronniesa It happens everytime after 24 hours.

**Comment by Mandur** [comment]
@maxstefaniv When I look at your docker inspect logs, I cannot see the environment variable ENABLE_GATEWAY set to false. May I ask to quickly double check. You can run 
`docker exec LoRaWanNetworkSrvModule bash -c printenv |grep ENABLE_GATEWAY`
(I am just double checking as it solved the issue for me)

I have a device that is running to try to get a repro, but at the moment I am failing to reproduce the problem, I think it might be benefical to have a call to look at the problem more in depth

**Comment by maxstefaniv** [comment]
@Mandur Sure I executed it. 
![image](https://user-images.githubusercontent.com/62515255/117932570-ccaa0b00-b300-11eb-929b-4dfe7b4d2326.png)

When are you available. I can add you to my Teams account and we can have a call.

**Comment by Mandur** [comment]
Sure @maxstefaniv just add me, we can sync add hoc!

**Comment by Mandur** [comment]
Following the discussion we are testing a new version with updated client librairies to see if that fix the issue

**Comment by maxstefaniv** [comment]
Applied update LoRaWanNetworkSrvModule from 1.0.5 to 1.0.5.1 on test edge, and it seems to help. If works on Prod edge as well, will close issue.

**Comment by Mandur** [comment]
As it seems our changes solved the issue, we merged this into dev. This fix will be be included in the next lorawan release.
Feel free to reopen if there are any more issues you face with it.

Thank you for raising this!

**Comment by maxstefaniv** [comment]
Effectively I was monitoring the situation through this weekend on both devices and there were no errors. All devices reauthenticate with gateways and there are no drops. This solution works. Thank you very much @Mandur.
