### ISSUE TITLE
Support for multiple LoRa Basic Station connected to 1 networkserver

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#345]
The solution needs to support multiple Concentrators for 1 IoT Edge Gateway

![image](https://user-images.githubusercontent.com/1822123/134162946-87f37916-c711-416d-84ef-a04863d4b5f7.png)

- [x] #385 
- [x] #402
- [x] #835

**Comment by Mandur** [comment]
Isn't that a duplicate of #348, or how do they differ?

**Comment by roel4ez** [comment]
@Mandur this is about having multiple connections to 1 gateway, where we have to build message selection, the caching and deduplication of messages. The other #348 is about splitting the LNS out of the edge devices. Or do you think this can be handled in the same Feature?
