### ISSUE TITLE
After 2-4h of no upstream messages, there are failures

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#347]
## Description

after 2-4h no more upstream msg There seems to be a bug, setting “AuthenticationMode” environment variable to "CloudAndScope" works for a while sometime just 1h and sometimes for a few hours…. and then is failing 

See also Issue [#4999 · Azure/iotedge](https://github.com/Azure/iotedge/issues/4999)

**Comment by Mandur** [comment]
I think that's a duplicate
