### ISSUE TITLE
Support for running LocalNetworkServer on a separate Edge or Cloud device

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#348]
## Description

We want to enable different scenarios by allowing the LNS to run on a different Edge Device, or even on another VM, both on-prem or in the cloud.

## Features:

- [x] #607 
- [x] #618

**Comment by Mandur** [comment]
I guess this one can be closed

**Comment by roel4ez** [comment]
> I guess this one can be closed

It depends. Maybe we should move the all stretch features to a new epic, which itself is marked as stretch?
