### ISSUE TITLE
Investigate and setup Codecov

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#366]
We want to get a good overview of the current state of the code coverage, and we want to be able to monitor the progress.

This story deals with investigating and setting up [Codecov](https://about.codecov.io/)

- ~~ADR with decision on how and why codecov is used~~
- [x] Investigate integration
- [x] Codecov is implemented in a GitHub action
- [x] Add coverage badge

**Comment by Mandur** [comment]
I am not sure we need an ADR for that, we could do this in the parking lot

**Comment by atifaziz** [comment]
Closed via #431, #432 and #434.
