### ISSUE TITLE
CUPS Firmware upgrade

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#394]
- [x] #1189
- [x] #1245
- [x] #1247
- [x] #1248
- [x] #1249
- [x] #1250
- [x] #1251
- [x] #1252
- [x] #1345
- [x] #1299

**Comment by roel4ez** [comment]
@mandur maybe it makes sense to take this story out and make it into its own feature inside #344

**Comment by MaggieSalak** [comment]
I think we can close this story @danigian @roel4ez ?
