### ISSUE TITLE
Adaptive Data Rate Support for CN470

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#419]
blocked until we clarified which region to support

**Comment by MaggieSalak** [comment]
PR merged https://github.com/Azure/iotedge-lorawan-starterkit/pull/572

**Comment by Mandur** [comment]
This one should be closed?

**Comment by MaggieSalak** [comment]
Yes, I will close it since it turned out that no changes are required for ADR in CN470.
