### ISSUE TITLE
[Story] Migrate static Logger methods to DI

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#456]
## Acceptance criteria

- [ ] The static `Logger` is removed
- [ ] All logging goes via `ILogger` and DI
- [ ] Logging sinks are migrated
- [ ] Catch all exceptions block ([in `UdpLogger.InitializeUdpLogger`](https://github.com/Azure/iotedge-lorawan-starterkit/blob/d4ffe15adb68fe8904097e08207ce23133a084b4/LoRaEngine/modules/LoRaWanNetworkSrvModule/Logger/Logger.cs#L246)) are removed
- [ ] Docs are up to date

**Comment by bastbu** [comment]
@atifaziz #740 is a possible task of this story tracked as a separate issue. Please close that issue as well if you resolve this.
