### ISSUE TITLE
Use `eclint` during CI to ensure basic conformance with `.editorconfig`

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#531]
Use [`eclint`](https://github.com/jedmao/eclint) in GitHub workflow (specifically `eclint check -w -n -c utf-8`) to ensure basic conformance with `.editorconfig` settings.

**Comment by roel4ez** [comment]
@mandur this story has no parent. I added it under #450

**Comment by danigian** [comment]
@Mandur, the eclint repository has been archived and last update is from a couple years ago.
Should we just remove this item?

**Comment by Mandur** [comment]
Sure, I don't think I created this story.

**Comment by Mandur** [comment]
Closing as discussed above
