### ISSUE TITLE
Using on ServiceFacadeHttpClientHandler cause object disposed exception

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#534]
Since we fixed the dispose error on the existing code, we added a using [here](https://github.com/Azure/iotedge-lorawan-starterkit/blob/b796a4fc1b986a213060e179cb840b7721da441d/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ServiceFacadeHttpClientProvider.cs#L31) that cause the E2E to fail (see below)

## Proposed course of action
let's ignore this error for now and use an injected httpclientfactory in the LBS evolution.

## Expected Behavior
This call should work

## Current Behavior
End to end test return error 
`17:32:23.661 [UDPLOG] [primary] 01F5A90000000011: failed to get join devices from api. Cannot access a disposed object.`
cf https://github.com/Azure/iotedge-lorawan-starterkit/runs/3897754806?check_suite_focus=true

## Steps to Reproduce
Run the E2E on dev

**Comment by p-schuler** [comment]
This was changed and we do no longer dispose it.
