### ISSUE TITLE
Deploying LoraKeysManagerFacade results in no functions

### ISSUE THREAD

**Issue by thomasvoorend** [Azure/iotedge-lorawan-starterkit#60]
After creating and deploying the function app with the Functions plugin in VS Code, there are no functions visible in the Azure Portal.

In the `.vscode/settings.json` I already adjusted the deploy path to: `LoraKeysManagerFacade/bin/Release/netstandard2.0/publish`

Does anyone know how to resolve this issue?

![nofunction](https://user-images.githubusercontent.com/32485864/49877030-d1fb8680-fe24-11e8-80c7-867e0a34f18a.png)

**Comment by fbeltrao** [comment]
Hi @thomasvoorend,

What works for me is opening VS Code in the function folder (LoRaEngine/LoraKeysManagerFacade) and then publish to Azure.

**Comment by thomasvoorend** [comment]
Hi @fbeltrao 
Thank you! That did the trick for me also!
