### ISSUE TITLE
Edge Hub, Edge Agent Metrics are collected and ingested in Log analytics

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#617]
- [ ] [Metrics collector](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-collect-and-transport-metrics?view=iotedge-2020-11&tabs=iothub) is deployed as part of the ARM template, test template and development template
- [ ] LogAnalytics workspace deployment
- [ ] New required environment variables are added to the deployment
- [ ] Metrics from edgeHub, edgeAgent and LNS are avalaible
- [ ] example.env file is changed to reflect the new variables
- [ ] Documentation is updated to describe the new functionality

**Comment by bastbu** [comment]
This is a duplicate of #739 and #255. Let's track the progress on this one in the other stories.
