### ISSUE TITLE
Multi concentrator cache

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#638]
## Context
Handle the race from multiple concentrators on the same edge device. Multiple concentrators will be potentially sending the same message from the same device. We only ever want to handle a single upstream message for a particular device on a edge (LNS).

We target 2 levels of deduplication:
1. deduplication of concentrator messages
2. deduplication of edge messages

Point 2 is already implemented today (utilizing the function and the redis cache in multi GW scenarios). Point 1 is new and should be added.

When we receive a message from the concentrator, we register the frame count up for that particular device. If it does not exist yet, we allow the message to continue, if it was already registered, we ignore the message.

## Acceptance criteria

- [x] #674
- [x] #724
- [x] #685
- [x] #686
- [x] #823
- [x] #824
- [x] #889

**Comment by spygi** [comment]
Re-opened because of the 2 open issues related to this.
