### ISSUE TITLE
Add support to configure LBS through command line

### ISSUE THREAD

**Issue by p-schuler** [Azure/iotedge-lorawan-starterkit#696]
## Description
To avoid configuration errors we should allow the provisioning and configuration of the LBS in IoT Hub through the Cli-LoRa-Device-Provisioning tool. 

## Acceptance criteria
- [x] #850
- [ ] Include CN470 RP1 region pre-configured template
- [ ] Include CN470 RP2 (20mhz plan B) region pre-configured template
- [ ] Add in documentation how to change default documentation json

stretch:
- [ ] Enable custom Json input for regional pararameters.

**Comment by p-schuler** [comment]
fyi @roel4ez @bastbu

**Comment by Mandur** [comment]
Contact me for frequencies
