### ISSUE TITLE
LBS device should be equivalent to LoRa device in IoT Hub

### ISSUE THREAD

**Issue by bastbu** [Azure/iotedge-lorawan-starterkit#697]
## Expected Behavior

The LBS devices in IoT Hub should have names equivalent to LoRa devices, which means that LBS device names should not need to have dashes.

## Current Behavior

Currently LBS device names need to include dashes, e.g. `DC-A6-32-FF-FE-B3-2F-C6`.

**Comment by roel4ez** [comment]
This needs a bigger discussion. Let's agree on this before starting @danigian @bastbu
