### ISSUE TITLE
[Story] Consider adding a JsonReader.Enum<T> for parsing values into existing enums

### ISSUE THREAD

**Issue by danigian** [Azure/iotedge-lorawan-starterkit#712]
## Description

As a comment from @bastbu in #711, we could implement a JsonReader.Enum<T> for parsing json values into enums.

**Comment by danigian** [comment]
Putting this into backlog
@atifaziz any comment on this?

**Comment by atifaziz** [comment]
> Putting this into backlog @atifaziz any comment on this?

It's a good idea.
