### ISSUE TITLE
IoT central investigation

### ISSUE THREAD

**Issue by spygi** [Azure/iotedge-lorawan-starterkit#723]
We want to understand better IoTCentral with the goal to eventually merge #360 

## Acceptance criteria
- Timebox understanding of IoT Central and potentially a brownbag

**Comment by bastbu** [comment]
@Mandur and I started to take a look at the PR. Some findings that we both had:
- We could not get OTAA with IoT Central to work on our machines, we would need to add documentation how we can make this work
- We would need to find a way to not fetch the device twins of all devices when provisioning an ABP device, as this might potentially be an expensive/chatty operation
- We would still need to check if the OTAA join checks the App Key of the device when a join request is issued

Something to consider: we could go through an ADR for IoT central support and then bring in the functionality piece by piece.
