### ISSUE TITLE
[Story] DwellTime support for AS923 ADR

### ISSUE THREAD

**Issue by MaggieSalak** [Azure/iotedge-lorawan-starterkit#732]
## Description

DwellTime is a parameter specific to AS923 region which can be either 0 or 1. We need to dive into this and find out if it needs to be set to 1 or not and calculate dependent values accordingly (e.g. max payload sizes are different in case it's set to 1).

**Comment by roel4ez** [comment]
@mandur can we pick this up? Is this the only story remaining to close out AS923 support?
