### ISSUE TITLE
"ClearCache" method issue

### ISSUE THREAD

**Issue by zhaozhenhong5** [Azure/iotedge-lorawan-starterkit#78]
> Cache Clearing
Due to the gateway caching the device information (tags) for 1 day, if the device tries to connect before you have provisioned it, it will not be able to connect because it will be considered a device for another LoRa network. To clear the cache and allow the device to connect follow these steps:

IoT Hub -> IoT Edge -> click on the device ID of your gateway
Click on LoRaWanNetworkSrvModule
Click Direct Method
Type "ClearCache" on Method Name
Click Invoke Method
Alternatively you can restart the Gateway or the LoRaWanNetworkSrvModule container.

I followed the step above,but it can't work.
I change to "clear cache",it can work but the gateway log is still here after I restart. 
Can you fix it?

**Comment by fbeltrao** [comment]
Thanks for the feedback.

What do you mean with "gateway log is still here after I restart"? Is this the log that the device is not ours or another one?

**Comment by zhaozhenhong5** [comment]
I mean that I can't delete the log of the gateway except I change to another gateway connection string. Then the log will become bigger,until more than the storage. Does the log can be deleted?

**Comment by fbeltrao** [comment]
Ok, you mean the container logs are long. There are few things you can do:

- Decrease log verbosity: to do that you change the LOG_LEVEL environment variable in the Network Server module (1 = logs everything, 2 = logs information and errors, 3 = logs errors only). NET_SRV_LOG_LEVEL in the env file contains the value (default is 1).

- Take a look at how you can clear or define a policy in docker to not run out of disk space: 
https://stackoverflow.com/questions/42510002/how-to-clear-the-logs-properly-for-a-docker-container

Please let us know if that solves the problem.

**Comment by fbeltrao** [comment]
@zhaozhenhong5 can I close this?

**Comment by zhaozhenhong5** [comment]
Yes,I close it.
