### ISSUE TITLE
How can I send all the devices messages to my application?

### ISSUE THREAD

**Issue by zhaozhenhong5** [Azure/iotedge-lorawan-starterkit#80]
Now I can received all my devices messages by the "iotedge-lorawan-starterkit" to the IotHub.  I need to send this to my application.Before I use TTN and it can POST this using Http method.[you can see here](https://www.thethingsnetwork.org/docs/applications/http/).
Can IotHub use this method?
Thank you.

**Comment by gerfen** [comment]
You'll need to create an Azure function which consumes an EventHubTrigger on a custom consumer group.  Visit the "Built-in endpoints" page for your IotHub and copy the "Event Hub-compatible endpoint".  You'll need this for the "Connection" parameter of the EventHubTrigger.  While you are on the "Built-in endpoint" page, create a new consumer group and record the name for the "ConsumerGroup" parameter.

![image](https://user-images.githubusercontent.com/5280484/51091973-0d9caf80-1747-11e9-91a3-e01136c33d0a.png)

Your function will look something like this: 
```    
[FunctionName("ForwardLoraData")]
public static async Task RunAsync([EventHubTrigger("%HubName%", Connection = 
        "RouterConnection", ConsumerGroup = "%ConsumerGroupForwardLoraData%")]EventData 
         eventData, ILogger log, ExecutionContext context)
        {
             var configuration = BuildConfiguration(context);
            var bodyBytes = eventData.Body.Array;
            var deviceId = GetDeviceId(eventData);
            var payload = GetPayload(bodyBytes);
            var requestUri = configuration[ConfigurationKeys.WebApiUrl];
            var httpClient = CreateHttpClient();
            var message = await httpClient.PostAsJsonAsync(requestUri, measurementViewModel);

             log.LogInformation(message.IsSuccessStatusCode
                ? $"ForwardLoraData: request sent successfully"
                : $"ForwardLoraData: request not sent successfully - {message.ReasonPhrase}");
        }

       private static HttpClient CreateHttpClient()
        {
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Accept.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            return httpClient;
        }

        private static string GetPayload(byte[] body)
        {
            var json = Encoding.UTF8.GetString(body);
            return json;
        }

        private static string GetDeviceId(EventData message)
        {
            return message.SystemProperties["iothub-connection-device-id"].ToString();
        }

        priate static IConfigurationRoot BuildConfiguration(ExecutionContext context)
        {
            return new ConfigurationBuilder()
                .SetBasePath(context.FunctionAppDirectory)
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();
        }
    }
```

**Comment by zhaozhenhong5** [comment]
Thanks for your reply. Can I add the function code you write above to my EventHubTrigger  in the Azure function? And what parameter shall I add? I want to post the gateway edge device data to my application(it has a URL address for being posted,how I add this URL to the code?)

**Comment by gerfen** [comment]
Create an Azure functions project in VS Code or Visual Studio.  

For local testing, add a file called local.settings.json to your function project.  Add the following:

```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",   
      RouterConnection": "<your iot hub connection string>",
     "WebApiUrl": "<your url>",
    "ConsumerGroupForwardLoraData": "<your consumer group>",
    "HubName": "lorawan-data",
  }
}
```

After you have tested your function locally,deploy it to Azure and set the same variuables except for "FUNCTIONS_WORKER_RUNTIME" in the application settings for functions project.

**Comment by zhaozhenhong5** [comment]
Sorry, I tried to do this with VS Code, but failed. I can't create an EventHubTrigger in the VS Code. One reason is that I am not familiar with the tool.
So, can you make this for me with VS Code and send to github?I think it's a easy thing to you.
Thanks very much!

**Comment by zhaozhenhong5** [comment]
Sorry again. I tried again but still fail to build. Another reason maybe I am not familiar with the C#, if python will do this job, it maybe good to me.  
I found that the VS Code haven't the "EventHubTrigger" to creat ,so I used Visual Studio to do this job.And here is my code [code](https://github.com/zhaozhenhong5/ForwardLoraData),the code report many error in Visual Studio,can you find the problem?
I need this funtion because I need the Azure-lorawan for my product. I must solve the problem as soon as possible.
Thank you.

**Comment by fbeltrao** [comment]
You need to install the [Azure Function Extensions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#install-the-azure-functions-core-tools).

In a new Azure Function project, enter this in the terminal:
`func extensions install --package Microsoft.Azure.WebJobs.Extensions.EventHubs --version 3.0.1`

This will add the package into the .csproj file.

Create new function using the Azure Function cli `func new` in VsCode terminal:

```
$ func new
Select a template:
1. QueueTrigger
2. HttpTrigger
3. BlobTrigger
4. TimerTrigger
5. DurableFunctionsOrchestration
6. SendGrid
7. EventHubTrigger
8. ServiceBusQueueTrigger
9. ServiceBusTopicTrigger
10. EventGridTrigger
11. CosmosDBTrigger
12. IotHubTrigger
Choose option:
```

**Comment by zhaozhenhong5** [comment]
@gerfen  Hello, in your sample code the "priate static IConfigurationRoot BuildConfiguration(ExecutionContext context)" shows error (error CS1585:Member modifier 'static' must precede the member type and name)
Do you know why?

**Comment by gerfen** [comment]
Most likely, you need to install Microsoft.Extensions.Configuration nuget package.  From the command line or the Terminal windows in vs code editor execute `dotnet add package Microsoft.Extensions.Configuration`.  You'll most likely need to do the same for Microsoft.Extensions.Logging.  

FWIW, here are all of the using statements you'll need at the top of your function:

```csharp
using Microsoft.Azure.EventHubs;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
```
And for completeness here is the code for the LoraMeasurement class.

```csharp
    public class LoraMeasurement
    {
        public string DeviceId { get; set; }
        public string GatewayId { get; set; }
        public string Json { get; set; }
    }
```

Feel free to modify as you see fit.

**Comment by gerfen** [comment]
Sur, you can hard code whatever you like.  You'll also need to hard code the parameters in the EventHubTrigger attribute.
```
 [FunctionName("ForwardLoraData")]
       public static async Task RunAsync([EventHubTrigger("%HubName%", Connection = 
      "RouterConnection", ConsumerGroup = "%ConsumerGroupForwardLoraData%")]EventData 
       eventData, ILogger log, ExecutionContext context)
```
to

```
 [FunctionName("ForwardLoraData")]
       public static async Task RunAsync([EventHubTrigger("<your hub nam>", Connection = 
      "<your connection string>", ConsumerGroup = "<your consumer group>")]EventData 
       eventData, ILogger log, ExecutionContext context)
```

**Comment by zhaozhenhong5** [comment]
So, can you find is it has something wrong in my code? It seems can't work well. Is the "application/json" need to be added? I changed "iothub-connection-device-id" to my gateway edge device name,right?

**Comment by gerfen** [comment]
You do not want to change that.   Are you able to set a break point and execute the code? Is the break point hit?  I don't have enough information to help you further at this point.

**Comment by fbeltrao** [comment]
I have created a sample app based on the good example given by @gerfen here: https://github.com/fbeltrao/Samples/tree/master/iothubforwarder

You need to change the local.settings.json file to:
- add a storage connection string (or use the development)
- add the iot hub event hub connection string

In the TelemetryToApp.cs file change:
- The consumer group used
- The destination URL

**Comment by zhaozhenhong5** [comment]
@fbeltrao @gerfen Thank you for your help!

**Comment by zhaozhenhong5** [comment]
I am testing this funtion today and find two problems as below:
1、It can working with VS Code, but deployed to the azure Funtion App, it can't. Is it need something to be set when deployed?
2、I found the IoT Hub messages posted to my application endpoint appear occur the delay,the delay I can see in the working VS Code. Just like the delay occur before when the devices messages sent to azure, this issue solved by fbeltrao before.
