### ISSUE TITLE
A new AzFunction endpoint should be added to send a class C message.

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#821]
If we[ currently want](https://azure.github.io/iotedge-lorawan-starterkit/dev/quickstart/#class-a-devices) to send a message to a class c device, we need to send a cloud to device message from IoT Hub targeting the right LNS, in addition with the recent changes we will need also to provide the correct concentrator.

expected parameters are the one of the LoRaCloudToDeviceMessage class. Fport, (payload || rawpayload) and DEVeui are mandatory.

The Idea here is to have an Azure function endpoint handling the class c message handling, the function should be able to:
 - [ ] PreferredGatewayID reported property need to be set to the current gateway id (=gateway ID) (in case there are no desired property GatewayID set) in case of upstream device message at the [same time as we set the stationEUI on upstream ](https://github.com/Azure/iotedge-lorawan-starterkit/blob/3043ae1c900390b84f0689fceb4a3478d56e537a/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs#L430)
 - [ ] Connect to IoT Hub to see what the device's assigned IoT Edge is and send the method to it (send it either to the desired property GatewayID or reported prop PreferredGatewayID)
 - [ ] Resolve to which concentrator to send the message (could be done on the LNS, the information is available [in the stationeui reported prop](https://github.com/Azure/iotedge-lorawan-starterkit/blob/ca99c726a6cf97d54118b825859067ec799cbe3f/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs#L173))
 - [ ] New code is unit/integration tested

**Comment by MaggieSalak** [comment]
Closing this story as it appears that the requested functionality is already implemented:
- `SendCloudToDeviceMessage` endpoint [already exists](https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/LoRaEngine/LoraKeysManagerFacade/SendCloudToDeviceMessage/SendCloudToDeviceMessage.cs) in the Facade project, which also supports class C devices and uses direct method to send the message to the correct gateway (retrieved from device twin). The endpoint [was added](https://github.com/Azure/iotedge-lorawan-starterkit/pull/147) back in March 2019. 
- Resolution of the correct concentrator is already done in the LNS. See [`OnDirectMethodCalled()`](https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/ModuleConnection/ModuleConnectionHost.cs#L86) which calls `DefaultClassCDevicesMessageSender` where the `loRaDevice.LastProcessingStationEui` is already added to the downlink message. Then the Station Eui is used in `DownstreamSender` to [retrieve the socket writer handle](https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/DownstreamSender.cs#L39).
- `PreferredGatewayID` reported property is already set for class C devices using the Function Bundler result in `DefaultLoRaDataRequestHandler`.
