### ISSUE TITLE
[Task] Document change from UDP- to TCP-based logging in release notes

### ISSUE THREAD

**Issue by atifaziz** [Azure/iotedge-lorawan-starterkit#825]
Story: #456

**Description**

Document the change from UDP- to TCP-based logging in release notes that was introduced with PR #789.

**Comment by danigian** [comment]
This was not documented in any release note, but TCP logging is part of the configuration documentation.
I would say we can close this.
@atifaziz please reopen if you think we should be more explicit in any docs
