### ISSUE TITLE
E2E testing with multiple concentrators

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#836]
## Acceptance Criteria

- [x] #838
- [x] change E2E tests to OTA devices (joins) - depends on #830 
- [x] Test with local setup
- [ ] enable E2E tests in CI

**Comment by MaggieSalak** [comment]
Enabling the test in the CI is tracked in https://github.com/Azure/iotedge-lorawan-starterkit/issues/871
