### ISSUE TITLE
Hex messages receive issue

### ISSUE THREAD

**Issue by zhaozhenhong5** [Azure/iotedge-lorawan-starterkit#84]
Can the engine receive the hex type lora payload? I tested it, but seems wrong.

**Comment by fbeltrao** [comment]
What is your input and actual/expected metric in IoT Hub?
The built-in decoder (DecoderValueSensor) works if the payload is a number. You might need to extend it by adding your own payload decoder.

The documentation is here: https://github.com/Azure/iotedge-lorawan-starterkit/tree/master/Samples/DecoderSample

**Comment by zhaozhenhong5** [comment]
Yes, I just saw this link. I have a question: How can I push DecoderSample to Azure Container?

**Comment by fbeltrao** [comment]
If you use the docker extensions in VsCode you can:

1. Right click on the dockerfile arm32v7 (for PI) and click Build Image. Enter the fullname of your Azure container instance: mycontainerinstance.azurecr.io/decodersample:1.0-armv32v7 (for example)

2. In VsCode you can right click on the built image and select "Push Image". The same can be done in command line by executing `docker push  mycontainerinstance.azurecr.io/decodersample:1.0-armv32v7`

**Comment by zhaozhenhong5** [comment]
Thank you. I had added the DecoderSample ,but it can only decod when the end-lora-device sending string  not the hex. Can change the decoder to decode hex?

**Comment by zhaozhenhong5** [comment]
Yes,thank you. The problems have solved.
